theme: jekyll-theme-leap-day
title: "Linux en Bioinfo"
description: "Une introduction rapide à linux"
show_downloads: true
data_url: "https://raw.githubusercontent.com/maclandrol/intro-linux/master/data.zip"
maintainer: "Emmanuel Noutahi"
